### ISSUE TITLE
Is this safe for production?

### ISSUE THREAD

**Issue by ThorodanBrom** [parallella/parallella-flash#1]
Hello,

I need to enable TFTP boot on a cluster of Parallellas. [This](https://elinux.org/TFTP_Boot_and_NFS_Root_Filesystems) is a guide that I was about to follow, but I noticed that these images provide exactly what I need to to do TFTP boot.

I just wanted to clarify whether the stock firmware will recognize a uEnv.txt file and utilize it ; or must I flash these images?

**Comment by olajep** [comment]
stock firmware will not recognize uEnv.txt.

**Comment by ThorodanBrom** [comment]
Thanks, so, in that case, can I flash these images safely? 

Another question, what's the difference between this repository, and the parallella u-boot one? Do I have to use parallella u-boot to generate uboot.elf ?

**Comment by olajep** [comment]
On Sun, Aug 5, 2018 at 3:56 AM ThorodanBrom <notifications@github.com>
wrote:

> Thanks, so, in that case, can I flash these images safely?
>

Safe in the sense that I have tested the instructions on at least three
(P1600 P1601 P1602) boards three years ago. No guarantees and if you
somehow brick a board you will need a parallella porcupine board and a zynq
compatible jtag programmer to fix it.

> Another question, what's the difference between this repository, and the
> parallella u-boot one? Do I have to use parallella u-boot to generate
> uboot.elf ?
>

The parallella-uboot repo is a parallella specific fork of xilinx-uboot.
There is already a working uboot.elf in the parallella-flash repo.

HTH,
Ola


>

**Comment by olajep** [comment]
Also see this related issue:
https://github.com/parallella/parallella-uboot/issues/5

You might have to add bootdelay=0 line to uEnv.txt

**Comment by ThorodanBrom** [comment]
Thanks for the help @olajep
